
LAUNCH_URL_REQUEST: str = "LAUNCH_URL_REQUEST"
LAUNCH_URL_RESPONSE: str = "LAUNCH_URL_RESPONSE"

LAUNCH_BOOKMARK_REQUEST: str = "LAUNCH_BOOKMARK_REQUEST"
LAUNCH_BOOKMARK_RESPONSE: str = "LAUNCH_BOOKMARK_RESPONSE"
